<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BDC6-DX-6BYDNK2" ignored="1" name="Suite_1" tests="14" failures="3" timestamp="17 Sep 2019 10:09:01 GMT" time="0.112" errors="0">
  <testcase name="f" time="0.006" classname="Day1.Demo1_TestNG"/>
  <testcase name="f1" time="0.003" classname="Day1.Demo1_TestNG"/>
  <testcase name="method1" time="0.023" classname="Day1.AssertClass_TestNG"/>
  <testcase name="method2" time="0.004" classname="Day1.AssertClass_TestNG"/>
  <testcase name="LogOut" time="0.035" classname="Day1.Demo2_TestNG"/>
  <testcase name="method3" time="0.007" classname="Day1.AssertClass_TestNG">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at Day1.AssertClass_TestNG.method3(AssertClass_TestNG.java:18)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- method3 -->
  <testcase name="method1" time="0.046" classname="Day1.SoftAssertion">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [11] but found [10],
	expected [hello] but found [Hello]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [11] but found [10],
expected [hello] but found [Hello]
at Day1.SoftAssertion.method1(SoftAssertion.java:15)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 11 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase name="method4" time="0.004" classname="Day1.AssertClass_TestNG"/>
  <testcase name="method5" time="0.001" classname="Day1.AssertClass_TestNG"/>
  <testcase name="method6" time="0.004" classname="Day1.AssertClass_TestNG"/>
  <testcase name="method7" time="0.001" classname="Day1.AssertClass_TestNG"/>
  <testcase name="method8" time="0.005" classname="Day1.AssertClass_TestNG">
    <failure type="java.lang.AssertionError" message="expected [null] but found [java.lang.Object@d5e576a]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [java.lang.Object@d5e576a]
at Day1.AssertClass_TestNG.method8(AssertClass_TestNG.java:47)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- method8 -->
  <testcase name="Register" time="0.001" classname="Day1.Demo2_TestNG"/>
  <testcase name="Login" time="0.002" classname="Day1.Demo2_TestNG"/>
  <testcase name="HomePage" time="0.0" classname="Day1.Demo2_TestNG">
    <ignored/>
  </testcase> <!-- HomePage -->
</testsuite> <!-- Suite_1 -->
