<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BDC6-DX-6BYDNK2" name="Day1.AssertClass_TestNG" tests="8" failures="2" timestamp="17 Sep 2019 10:09:01 GMT" time="0.049" errors="0">
  <testcase name="method3" time="0.007" classname="Day1.AssertClass_TestNG">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at Day1.AssertClass_TestNG.method3(AssertClass_TestNG.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- method3 -->
  <testcase name="method7" time="0.001" classname="Day1.AssertClass_TestNG"/>
  <testcase name="method4" time="0.004" classname="Day1.AssertClass_TestNG"/>
  <testcase name="method5" time="0.001" classname="Day1.AssertClass_TestNG"/>
  <testcase name="method1" time="0.023" classname="Day1.AssertClass_TestNG"/>
  <testcase name="method2" time="0.004" classname="Day1.AssertClass_TestNG"/>
  <testcase name="method8" time="0.005" classname="Day1.AssertClass_TestNG">
    <failure type="java.lang.AssertionError" message="expected [null] but found [java.lang.Object@d5e576a]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [java.lang.Object@d5e576a]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotSame(Assert.java:772)
at org.testng.Assert.assertNull(Assert.java:708)
at org.testng.Assert.assertNull(Assert.java:697)
at Day1.AssertClass_TestNG.method8(AssertClass_TestNG.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- method8 -->
  <testcase name="method6" time="0.004" classname="Day1.AssertClass_TestNG"/>
</testsuite> <!-- Day1.AssertClass_TestNG -->
